
sudo: false
language: node_js
node_js:
- stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm test -- --coverage -w 2 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
